<<<<<<< HEAD
services:
  - type: web
    name: node-ejs-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
=======
services:
  - type: web
    name: node-ejs-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
>>>>>>> 42a3d4d (Remove node_modules and lock file for Render deployment)
